exclude: ^(legacy|doc|data|models|notebooks|ignore)/
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: flake8
        args: [--statistics]

-   repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
    -   id: black
        entry: black
        # exclusion rules for black defined in pyproject.toml are ignored by pre-commit,
        # so they must be copied here
        exclude: pipeline_plate_settings.py

-   repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
    -   id: isort
